apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-request-service
  namespace: erp
  labels:
    app: approval-request-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-request-service
  template:
    metadata:
      labels:
        app: approval-request-service
    spec:
      containers:
        - name: approval-request-service
          image: infra-approval-request-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: MONGODB_DB_NAME
              value: erp
            - name: MONGODB_COLLECTION_NAME
              value: approvals
            - name: EMPLOYEE_SERVICE_BASE_URL
              value: http://employee-service.erp.svc.cluster.local:8000
            - name: APPROVAL_PROCESSING_GRPC_TARGET
              value: approval-processing-service:50051
            - name: NOTIFICATION_SERVICE_BASE_URL
              value: http://notification-service.erp.svc.cluster.local:8000
            - name: RABBITMQ_URL
              value: amqp://erpuser:erppassword@rabbitmq:5672/