apiVersion: v1
kind: Service
metadata:
  name: approval-request-service
  namespace: erp
spec:
  selector:
    app: approval-request-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
